### ISSUE TITLE
Typescript compilation error

### ISSUE THREAD

**Issue by DominiqueBertrand** [apollostack/GitHunt-angular2#20]
I got the following error:

ERROR in /Users/BenQ/WebstormProjects/GitHunt-angular2/node_modules/apollo-client/QueryManager.d.ts
[1] (15,28): error TS2503: Cannot find namespace 'NodeJS'.

---------------
npm -version: 3.9.3

**Comment by kamilkisiela** [comment]
I'm on it now.

In the meantime, you can use 

```bash
typings i -SG dt~node
```

**Comment by DominiqueBertrand** [comment]
@kamilkisiela thank you. It is working well now!
