### ISSUE TITLE
error when trying to run

### ISSUE THREAD

**Issue by Tallyb** [apollostack/GitHunt-angular2#22]
Uncaught No provider for Token Platform Pipes! (CompilerConfig -> Token Platform Pipes)

**Comment by kamilkisiela** [comment]
@Tallyb #23 should fix it. There are many breaking changes in RC5...

**Comment by Tallyb** [comment]
@kamilkisiela  infact, i just did npm install and it was on rc2...

**Comment by kamilkisiela** [comment]
I moved to RC4 and it seems ok. Could you check it?

Please also remove `node_modules`

**Comment by Tallyb** [comment]
like a charm! now RC5...

**Comment by kamilkisiela** [comment]
@Tallyb I created an issue #30. Feel free to help with it! :sos:
