### ISSUE TITLE
Use service instead of decorator

### ISSUE THREAD

**Issue by kamilkisiela** [apollostack/GitHunt-angular2#34]
`Angular2Apollo.watchQuery` instead of `@Apollo(queries)`

and

`Angular2Apollo.mutate` instead of `@Apollo(mutations)`

**Comment by Tallyb** [comment]
is that what is shown in the documentation? http://docs.apollostack.com/apollo-client/angular2.html#angular2apollo

**Comment by kamilkisiela** [comment]
Yes but this is only an idea. It will be discussed soon, after we manage to get more stable API

**Comment by Tallyb** [comment]
mmmm.... having it already in the documentation if it does not exist yet is confusing to people who will want to try. Should be clearly marked.

**Comment by kamilkisiela** [comment]
No no. It's working and everything. What I meant is I don't know what would be better for GitHunt example, the service or the decorator.  That's the point.

**Comment by kamilkisiela** [comment]
Service seems pretty much done, the functionality. Decorator stayed behind but I'm currently working on it :)

**Comment by Tallyb** [comment]
@kamilkisiela  probably mix them both so people can get a feeling of what they are like

**Comment by kamilkisiela** [comment]
@Tallyb We will go with `Angular2Apollo` service until we figure what is the future of `Apollo` decorator. Not the future of decorator existence but about how it would work and what would be the best API etc.

**Comment by kamilkisiela** [comment]
If someone wants to see `Apollo` decorator works in action he can go to [`decorator`](https://github.com/apollostack/GitHunt-angular2/tree/decorator) branch.
