### ISSUE TITLE
getting error: has no exported member 'ModuleWithProviders'

### ISSUE THREAD

**Issue by vonwao** [apollostack/GitHunt-angular2#39]
ERROR in /Users/vonwao/psq/app/node_modules/angular2-apollo/build/src/ApolloModule.d.ts
(1,10): error TS2305: Module '"/Users/vonwao/psq/app/node_modules/@angular/core/index"' has no exported member 'ModuleWithProviders'.

**Comment by kamilkisiela** [comment]
Is it still a thing?

**Comment by kamilkisiela** [comment]
Maybe you use Angular in lower version than RC5?

**Comment by kamilkisiela** [comment]
Closing, but please @mention me if you think this should be still opened.

**Comment by AIP93** [comment]
Hello...
Has no exported member 'ModuleWithProviders' .
Help me please.

**Comment by Ukmandal** [comment]
$ npm start

> angular-quickstart@1.0.0 prestart C:\Users\Man\project\my-proj
> npm run build


> angular-quickstart@1.0.0 build C:\Users\Man\project\my-proj
> tsc -p src/

src/app/app.routing.ts(1,9): error TS2305: Module '"C:/Users/Man/project/my-proj/node_modules/@angular/core/core"' has no exported member 'ModulewithProviders'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Man\AppData\Roaming\npm-cache\_logs\2017-11-30T05_25_12_114Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Man\AppData\Roaming\npm-cache\_logs\2017-11-30T05_25_12_234Z-debug.log
