### ISSUE TITLE
Cannot find module 'graphql/language/printer'

### ISSUE THREAD

**Issue by jboothe** [apollostack/GitHunt-angular2#6]
App is definately working better. There is, however, the following error present in the console:

![screen shot 2016-07-01 at 8 29 01 pm](https://cloud.githubusercontent.com/assets/3723481/16537217/27f466c6-3fcb-11e6-9053-9dfe894db858.png)

**Comment by kamilkisiela** [comment]
It looks like a problem with `apollo-client` by itself. I'll dive into it tomorrow :+1:

**Comment by kamilkisiela** [comment]
apollostack/graphql-tag#5
