### ISSUE TITLE
[HPM] PROXY ERROR: ECONNREFUSED.

### ISSUE THREAD

**Issue by volkrass** [apollostack/GitHunt-angular2#63]
I installed GitHunt like described, but I'm facing this issue:

On http://localhost:3000/  I see "Loading..." on the right top corner, but can't login. 

On  the console:
[HPM] PROXY ERROR: ECONNREFUSED. localhost -> http://localhost:3010/graphql
Any advice?

**Comment by kamilkisiela** [comment]
It seems like you didn't use [GitHunt-API](https://github.com/apollostack/GitHunt-API).

You have to run it first.
