### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by NathanielMalca** [apollostack/GitHunt-angular2#74]
Hey,

After npm start all the files are wraped in main.bundle.js with no possiblity to add break point on code.

How can we break the code to components and for it to be debuggable?

Thanks

**Comment by KordonDev** [comment]
If you use Chrome you find on the source tab different sources on the left. There you select `webpack://` and your local folder. Here you can find your source files and add breakpoints to it.

![screen shot 2016-11-17 at 11 34 11](https://cloud.githubusercontent.com/assets/5114919/20386048/2993a9cc-acba-11e6-926e-71b18f9988c6.png)

**Comment by NathanielMalca** [comment]
from some reason , I don't have the Users folder @KordonDev 
![screenshot from 2016-11-18 14-06-00](https://cloud.githubusercontent.com/assets/17062686/20429587/4087e2d6-ad98-11e6-8970-cbb6d16ab2bd.png)

**Comment by KordonDev** [comment]
Users folder is macOs specific. It looks like you are using linux where you will find your sources under `home/`.

From your screenshot I would guess your sources are lying under `home/angel/Downloads/apollo client/GitHunt-angular2`.

**Comment by NathanielMalca** [comment]
nope. i wish it was that easy. i use linux indeed but the sources arent there . the only place i can find it is in the main bundle but its hard to debug like that. there needs to be some configuration in webpack to achieve that but the problem is that i dont know how  :/ @KordonDev 
![screenshot from 2016-11-18 22-32-54](https://cloud.githubusercontent.com/assets/17062686/20445732/fe8747d6-adde-11e6-9998-230ff1c8f7b9.png)

![screenshot from 2016-11-18 22-26-57](https://cloud.githubusercontent.com/assets/17062686/20445553/35601388-adde-11e6-95d8-c31a3d0d82b2.png)

**Comment by kamilkisiela** [comment]
It's based on `angular-cli` so it's not GitHunt-Angular2 specific.

See this https://github.com/angular/angular-cli/issues/2453
