### ISSUE TITLE
yarn.lock wildly out of date

### ISSUE THREAD

**Issue by intellix** [apollostack/GitHunt-angular2#83]
I'm getting errors in my project using angular2-apollo and figured I'd check this project out to see what the difference is to mine. Doing a `yarn` I get a bucket of errors about inabilities to resolve `graphql`.

Two solutions:
 - delete yarn.lock and run yarn
 - run npm i

package.json - updated 2hrs ago
yarn.lock - updated 2months ago

**Comment by kamilkisiela** [comment]
or 

```
$ yarn upgrade
```

which I did in #84
